### ISSUE TITLE
Triple-quoted strings result in an error

### ISSUE THREAD

**Issue by mgeisler** [thomaseizinger/set-crate-version#2]
Hi there!

When trying to set the version number for a crate (my [lipsum crate](https://github.com/mgeisler/lipsum)) which uses triple-quoted strings, I get an error:

    Error: Mismatch between location and raw string, expected 7 lines for """"
    Lipsum is a lorem ipsum text generation library. Use this if you need
    filler or dummy text for your application.

    The text is generated using a simple Markov chain, which you can also
    instantiate to generate your own pieces of pseudo-random text.
    """"

The `Cargo.toml` file has a triple-quoted description:

```toml
[package]
name = "lipsum"
version = "0.8.0"
authors = ["Martin Geisler <martin@geisler.net>"]
description = """
Lipsum is a lorem ipsum text generation library. Use this if you need
filler or dummy text for your application.

The text is generated using a simple Markov chain, which you can also
instantiate to generate your own pieces of pseudo-random text.
"""
documentation = "https://docs.rs/lipsum/"
repository = "https://github.com/mgeisler/lipsum/"
readme = "README.md"
````

To the best of my knowledge, this is a valid TOML file, but it somehow triggers the above error. I wasn't able to figure out what the problem is.
